### PR TITLE
Dynamically added images fix

### PR DESCRIPTION
**Pull request by alexdrimbe**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Just a note that the lint fixes are already in #75. I don't mind rebasing myself or you @alexdrimbe.

**Comment by XhmikosR** [comment]
This needs a rebase and skip the unneeded patches.

**Comment by feimosi** [comment]
I agree, @alexdrimbe could you take care of that?

**Comment by alexdrimbe** [comment]
Yes, I will take care of it.

**Pull request closed without merging**
