### PR TITLE
(docs) Update README.md

### PR DESCRIPTION
**Pull request by leibrug**
Fix formatting in table of options - `filter` row

### CODE REVIEW

**Comment by feimosi** [comment]
Thanks for spotting that! Would you mind renaming the commit message `(doc)` -> `(docs)` ? Just for my OCD 😄

**Comment by feimosi** [comment]
I meant the Git commit message (with `git commit --amend`), thanks!

**Comment by leibrug** [comment]
Is it OK now? :)

**Comment by feimosi** [comment]
Seems fine, thanks for contributing :)

**Pull request merged**
