### PR TITLE
Fix IE regression

### PR DESCRIPTION
**Pull request by XhmikosR**
@feimosi: things still break on IE8 due to `overlayBackgroundColor: 'rgba(0,0,0,.8)'` since IE8 doesn't support it. This is an old issue, not a regression.

How do you want to solve this?

### CODE REVIEW

**Comment by feimosi** [comment]
A simple ` if (overlay.style.backgroundColor) ` will suffice. Strange I haven't detected it earlier.

I think we should hold off with `svg`. It's kind of a breaking change.

Could you break polyfills change into a new PR? A prefer atomic changes.

**Comment by XhmikosR** [comment]
Kept only the IE error fix.

The check you suggest is moot IMO. The problem is rgba and browsers that don't support it.

A `try`/`catch` seems to do the job, but I'm not sure we want to go that way.

**Comment by XhmikosR** [comment]
Unless you want a new function to feature test if RGBA is supported.

I'd say at this point, we might just use try/catch since v2.0 won't support old browsers.

**Comment by XhmikosR** [comment]
So @feimosi, do you want me to do a try/catch or you want to try another approach yourself after merging this?

**Comment by feimosi** [comment]
Ok, let's use the `try/catch` solution. I first thought it's the `backgroundColor` property issue, not it's value. Not I got it.

**Comment by XhmikosR** [comment]
@feimosi: it seems that since we already have the fallback in the CSS, we were overriding `overlayBackgroundColor` in JS.

Can you check the last patches and let me know which solution you prefer so that I rebase it?

**Comment by feimosi** [comment]
Sorry, I don't understand the last patch. Why have you eventually got rid of the `try/catch` ? 
I think it'd work well that way. If we encounter IE8, the error is thrown, no value is set to _overlayBackgroundColor_ and the CSS fallback is used, right? The _rgba_ color could either be in JS only or on both CSS and JS files.

**Comment by XhmikosR** [comment]
@feimosi: there are different issues.

1. IE 8 throws an error due to `rgba`.
2. We already set the `background-color` for `#baguetteBox-overlay` in the CSS
3. Without the last patch, the `overlayBackgroundColor` option had no effect

So, I can add a try/catch for the case someone passes rgba and IE8. But we still need the last patch for the third point above.

**Comment by XhmikosR** [comment]
Actually, scratch the last point; I was looking into the wrong gallery :/

OK, so try/catch should do the job.

**Comment by feimosi** [comment]
Ok, it's alright now. I'm gonna make the patch release (1.6.1) later today.

**Comment by XhmikosR** [comment]
Cool, don't forget to update the gh-pages branch.

You could add gulp-gh-pages if you want.

**Comment by feimosi** [comment]
Done. Thanks for letting know such plugin exists :+1:

**Pull request merged**
