### PR TITLE
Tweak README.md.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by feimosi** [comment]
Everything's perfect except the badges. I've put dependencies (which are of course empty) on purpose, to show that the script indeed is self -contained, without any '3rd parties'. I'm not sure ordinary developers, who just want to use it, are interested in seeing devDependencies status. What do you think?

**Comment by XhmikosR** [comment]
Hmm, it's a little non-standard. We can add a separate badge for that. shields.io allows to add custom badges. Can you look at that and choose something to put then?

**Comment by feimosi** [comment]
Okay, so how about keeping both badges: dependencies and devDependencies. Actually the first one could be a static image, to keep the blue color theme:
Dependency Status

**Comment by XhmikosR** [comment]
You can make all that with shields.io dynamically :)

https://img.shields.io/badge/dependencies-NONE-blue.svg

**Comment by XhmikosR** [comment]
@feimosi: please check now.

**Comment by feimosi** [comment]
@XhmikosR  everything's fine.

**Pull request merged**
