### PR TITLE
Losslessly compress images with kraken.io.

### PR DESCRIPTION
**Pull request by XhmikosR**
```
Before: 9,16 MB (9.612.700 bytes)
After:  9,00 MB (9.437.932 bytes)
```

### CODE REVIEW

**Comment by feimosi** [comment]
I'm not sure if it's needed here. First of all, it was my mistake to put these blobs into the repository (could have used some cdn). That makes it particularly huge for such a small library. Now, every change to the images just makes the repo size grow (I'm just not sure by how much though). Secondly, it's not such a big gain for a demo-page. Also bigger images give us a chance to see the working spinner ;)

**Comment by XhmikosR** [comment]
Well, GitHub is behind a CDN anyway.

As for the repo size, sure it will increase, but I doubt it's an issue for such a small repo.

And the differences aren't huge so one can still see the loader (if they're lazy to throttle the connection :p).

Alternatively, we can only compress the thumbnails.

**Comment by feimosi** [comment]
I meant, every time someone clones the repo - it's over 10MB to download. But now I remembered there's something like .npmignore, so eventually it's fine to approve this PR :)

**Comment by XhmikosR** [comment]
That is for your npm package, yes.

I wouldn't use npmignore, just specify the `files` property in package.json for the dist files only.

**Comment by feimosi** [comment]
Ok, thanks.

**Pull request merged**
