### PR TITLE
Add Body Class and Ignore Class

### PR DESCRIPTION
**Pull request by davidhellmann**
Hey, here is a new Pull Request. Now you can see it better I hope :)
Sorry for the late response!

### CODE REVIEW

**Comment by feimosi** [comment]
No problem, thanks! There are a few linter errors, could you take a look?
https://travis-ci.org/feimosi/baguetteBox.js/jobs/195095908#L188

**Comment by XhmikosR** [comment]
@feimosi: just fix them yourself and push to @davidhellmann fork and then just squash + merge.

**Comment by feimosi** [comment]
I can't push to other's forks without some extra permission, can I?

**Comment by XhmikosR** [comment]
Yep you can. This is the default option for PRs opened like in the last
year. See the command line instructions in a PR in a project of yours :)

**Comment by feimosi** [comment]
@XhmikosR Interesting, thanks! :)

**Comment by XhmikosR** [comment]
@feimosi: I replied via email but you probably missed it.

>Now regarding this PR... are you sure all supported browsers have classList support?
>We should add ESLint plugin compat to automate this.

**Comment by feimosi** [comment]
@XhmikosR I didn't get that message.
Anyway, I've added an extra check for classList support here:
https://github.com/feimosi/baguetteBox.js/pull/143/files#diff-4634650f8cf2cdceb34291a9bcf4c23fR472

I'll test test thoroughly before the next release too.

**Comment by XhmikosR** [comment]
@feimosi: I wouldn't personally go with that. If you still want to support < IE 9 you should do this https://plainjs.com/javascript/attributes/adding-removing-and-testing-for-classes-9/

**Comment by feimosi** [comment]
Sure, it works only in newer IE, but using this option won't break anything, so I don't see any hazard here. Treat it as progressive enhancement, I just need to mention that in the docs.

**Pull request merged**
