### PR TITLE
scss to stylus

### PR DESCRIPTION
**Pull request by blynx**
just added a stylus file
converted via http://sass2stylus.com

### CODE REVIEW

**Comment by feimosi** [comment]
Hi, could you explain more about the reason behind this pull request? Maintaining two style files would be cumbersome and I don't need to switch to Stylus. Also what conventions does the first commit solve?

**Comment by feimosi** [comment]
No response and there's no need for Stylus in this project, so I'm closing the PR.

**Comment by blynx** [comment]
uaaa - wanted to respond - totally forgot. Yep, you're right actually. I'll just maintain my own fork for so long with stylus. Sorry for the confusion, cheers!

**Comment by feimosi** [comment]
Ok, good that we've cleared that out. Cheers!

**Pull request closed without merging**
