### PR TITLE
Fix validation errors.

### PR DESCRIPTION
**Pull request by XhmikosR**
Also bump copyright year, minor tweaks.

@feimosi: I didn't know about the other images so I just added an empty `alt`. It's not totally correct but it's valid at the moment.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Also fixed an issue for mobile phones due to `width` set for `pre`; I changed it to `max-width`.

**Comment by feimosi** [comment]
Did you put the `alt` just for the code to be semantically valid ? We can write something like _Image 3.1_ etc.

**Comment by XhmikosR** [comment]
I didn't know what each image is so I just added an empty alt to make everything valid. I'd prefer if we added real alt values.

**Comment by XhmikosR** [comment]
Please check now.

**Comment by feimosi** [comment]
I'd add real values if I could, but that needs some extra time for researching and it's just a demo page of lightbox. For now it's all enough.

**Comment by XhmikosR** [comment]
By real values I meant not empty :p

**Comment by feimosi** [comment]
Oh ok, I thought you meant the descriptions of what the pictures show.

**Pull request merged**
