### PR TITLE
(feat) Add passive mode support for touch events

### LINKED ISSUE #142: Google lighthouse report
So, when testing with [Google's lighthouse app](https://github.com/GoogleChrome/lighthouse), I get the following coming from baguetteBox.

```
JavaScript: Site uses passive listeners to improve scrolling performance.
Consider marking your touch and wheel event listeners as passive to improve your page's
scroll performance.

    https://feimosi.github.io/baguetteBox.js/js/baguetteBox.js (line: 91, col: 37)

    div#baguettebox-overlay.addEventListener('touchstart', function (event) {
        touch.count++;
        if (touch.count > 1) {
            touch.multitouch = true;
        }
        // Save x and y axis position
        touch.startX = event.changedTouches[0].pageX;
        touch.startY = event.changedTouches[0].pageY;
    })
```

The learn more link is https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

I thought I'd bring it to your attention.

### PR DESCRIPTION
**Pull request by feimosi**
Resolves #142

Still needs some testing on mobile devices.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@feimosi: Is there anything left for this to get merged?

**Comment by feimosi** [comment]
Sorry for my late reply. Not all browsers support the `options` argument to the `addEventListener`. I need to test it first so nothing breaks.

**Comment by XhmikosR** [comment]
@feimosi: if you still want to support IE8, then `addEventListener` won't work there at all. You will need to use `attachEvent` instead.

**Comment by feimosi** [comment]
I've got `attachEvent` fallback in the `bind` method already.
The problem with `options` is, even Edge doesn't support it, so it may treat the object as a truthy value for `useCapture`. I need to add feature detection code, but it'll increase the size of the script.

**Pull request merged**
